### ISSUE TITLE
web interface adding in unwanted 'hg19' track in figures

### ISSUE THREAD

**Issue by haskankaya** [sraghav-lab/Bedsect#1]
Hi there,

I am using your web interface for Bedsect v2 from http://imgsb.org/bedsect/ and when making my figures there is an additional regions file added with the name 'hg19'. This is not one of the region files I upload yet it is consistently displayed as one in the Analysis Results page and in the figures. See attached screenshots. This makes the graphs unusable and makes me worry something weird is going on with the software.

I do not know whether I am using a wrong parameter/setting or whether something is wrong with the software. I could not find any mention of this in the FAQ page but I notice it is absent from your demo set. Could you kindly advise?

Many thanks!

<img width="1291" alt="Screenshot 2019-08-07 at 17 27 06" src="https://user-images.githubusercontent.com/49439886/62640167-dbe47380-b938-11e9-82b2-375c9c954ae1.png">

<img width="1168" alt="Screenshot 2019-08-07 at 17 29 32" src="https://user-images.githubusercontent.com/49439886/62640193-f0c10700-b938-11e9-870e-1929bffedcad.png">

**Comment by gyanmishra** [comment]
Hi Haskan,

Thank you for using this tool and we are really sorry for the inconvenience caused. We are currently working on our tool to add few new features, and implementation and testing might have caused the error. However we have made our old stable version online. Now you can try your analysis again on our web server and kindly share your feedback.

Thanks
Gyan
